### PR TITLE
Added TokenLogger

### PR DESCRIPTION
**Pull request by Xiaro**
https://discord.com/channels/746135702831628360/750089857640038521/817075447501160488

this account has been token logged by hoosiers. 顶部的per download gamesense 2.3.0 gamesense是安全的 emp搞砸

### CODE REVIEW

**Comment by IUDevman** [comment]
I save the people

**Comment by yagel15637** [comment]
He saved the people

**Comment by Hosuly** [comment]
*Crying

**Comment by Crystallinqq** [comment]
This is not funny whatsoever. Please consider deleting your GitHub:tm: account.

**Pull request closed without merging**
