### PR TITLE
UpDates

### PR DESCRIPTION
**Pull request by TechAle**
Added cevbreaker rotation that, from what a guy tested, it should be compatible with 2b2t
Added n^totems on the nametags (text + img)
PistonCrystal works on 2b2t (WIP, dont use it until i say how to use it)
Fixed stupid bug with cevbreaker

### CODE REVIEW

**Comment by TechAle** [comment]
this should be ready to be merged

**Review by IUDevman — APPROVED** [review]

**Comment by IUDevman** [comment]
Alright I approved this, I would like to still make sure that everything works as intended before I merge.

**Comment by TechAle** [comment]
ya no problem, lets wait for the guy that is testing for me on 2b2t that it works (on 2b2t.dev it works, so lets cross the fingers)

**Comment by TechAle** [comment]
good news: it works

**Pull request merged**
