### PR TITLE
PistonCrystal update

### PR DESCRIPTION
**Pull request by TechAle**
Fix:    1) Fixed that the y-level didnt count -1
            2) Fixed the bug that place the redstone before the crystal, now it never get stuck
            3) Fixed bug where it was trying to place a crystal in a place that is 1*1 (crystal is 1*2)

    Added:  1) NoGlitchPlace mode

    Misc:   1) Cleanup update function
            2) A lot of comments
            3) Merge

### CODE REVIEW

**Comment by TechAle** [comment]
bruh what

**Comment by TechAle** [comment]
on my pc works,
i checked why here not and that's why:
`* What went wrong:
A problem occurred configuring root project 'gamesense-client'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT.
     Required by:
         project :
      > Could not resolve net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT.
         > Unable to load Maven meta-data from http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.3-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.3-SNAPSHOT/maven-metadata.xml'.
               > Connect to files.minecraftforge.net:80 [files.minecraftforge.net/142.44.226.189, files.minecraftforge.net/2607:5300:60:84db:0:0:0:0] failed: Network is unreachable (connect failed)`
it's not a client problem

**Comment by yagel15637** [comment]
Yep, it failed on Decomp Workspace, I'd check it on your PC before merging just to make sure tho @IUDevman

**Comment by IUDevman** [comment]
Seems like a library was down, which is not surprising that happens every once and a while. I re-ran the job and everything is fine.

**Pull request merged**
