### PR TITLE
Fixed Auto Anvil and Piston Crystal

### PR DESCRIPTION
**Pull request by ghost**
Although it won't compile, I believe this is the relevant fix. Sorry, i though sur_block was only a local variable!

### CODE REVIEW

**Comment by IUDevman** [comment]
I'll merge this when it compiles :P

**Comment by 0b00101010** [comment]
Thanks, sorry about this

**Comment by TechAle** [comment]
AutoAnvil works fine, its just PistonCrystal i think

**Comment by 0b00101010** [comment]
Yeah it used sur_blocks elsewhere in the code and i didnt notice
Auto Anvil also uses sur_blocks when creating the structure, but it may not have an effect?

**Comment by TechAle** [comment]
Uh i dont think it affect, i used it tomorrow and it was fine, ill keep an eye when everything will work

**Pull request merged**
