### PR TITLE
Predict to CA

### PR DESCRIPTION
**Pull request by R-33**
I've been testing it out on 2B pvp for a while. It seems to work well in some scenarios like when someone is chasing you it normally pops them.

The bugs I've seen so far are seemingly random place positions and render crystal damage visuals. I think the random places happen due to the target strafing where theyre not looking. No idea why the visuals are so random.

It's not ready for a stable release but idk you guys may wanna look into tweaking it more.

### CODE REVIEW

**Comment by IUDevman** [comment]
Let's work some more on making the prediction a bit more inaccurate. I'll reopen this once 2.2.6 is released.

**Comment by R-33** [comment]
yeah I have a few ideas. I think the main issue comes from it predicting based on player movement and the direction the player is facing. So if someone is facing forwards and theyre strafing right it will predict forward instead of diagonally. I think I can get around this by using mc.player.posX and mc.player.prevPos X for example. Ill look into it when you decide to reopen this pr

**Comment by IUDevman** [comment]
I'm willing to look into this again if you:
1. Updated this to the latest build in the 2.2.7 branch
2. Make it so that it only triggers if a player is moving

**Comment by R-33** [comment]
Sounds good I'm fairly busy at the moment with other projects but I can look to getting around to it within the next week or so

**Pull request closed without merging**
