### PR TITLE
V2.3.0 InstaBurrow.java 

### PR DESCRIPTION
**Pull request by TalentedToad**
i found this off github and i checked the code and it looks good no viruses i just need one of the devs to import it
[InstantBurrow-master.zip](https://github.com/IUDevman/gamesense-client/files/6176673/InstantBurrow-master.zip)

### CODE REVIEW

**Comment by XdFag** [comment]
as the devs once said "no burrow"

**Comment by TechAle** [comment]
a) We dont want burrow in gamesense
b) you dont know how to use github

**Comment by IUDevman** [comment]
LOL

**Comment by notperry1234567890** [comment]
> i found this off github and i checked the code and it looks good no viruses i just need one of the devs to import it
> [InstantBurrow-master.zip](https://github.com/IUDevman/gamesense-client/files/6176673/InstantBurrow-master.zip)

HAHAHA

**Pull request closed without merging**
