### PR TITLE
Added OffHand + AutoTrap bug fix

### PR DESCRIPTION
**Pull request by TechAle**
Fixed bug #101 
New module: OffHand
options:
-Default + non default Item (if you are >Health, default is going to be active)
In these 2 options, you can choose between: Totem, Crystal, Gapple, Pot, Plates.
- potionChoose, with this you can choose which potion is going to be in your offHand
3 options: first, strength, speed
- healtSwitch, for choosing between default and non-default
- tickDelay, for the switch of the items
- fallDistance, if you fall more then fallDistance, a totem will be put on your offHand
- biasDamage, choose how much you wanna be safe with crystalCheck
- swordGap, if you left click with a sword, a gap will be in your offHand
- swordPot, if you shift with a sword, a potion will be in your offHand
- fallDistanceBol, active/deactive faillDistance check
- crystalCheck, check if a crystal can be lethal for you
Edit after commit 8182327:
- New algo for crystalCheck (it works)
- Added obbySwitch (if you are left-clicking a crystal, it's going to switch your offhand to an obby)
- Added antiWeakness (if you have weakness, it's going to put on your offhand a crystal)
- Added nonHotbar (if you enable this, it wont take items from your hotbar)
Edit after 43dd20d
- Added sword check option

### CODE REVIEW

**Comment by Doogie13** [comment]
Is it possible to add a mode which detects CA? So you don't offhand a crystal if you aren't using CA.

**Comment by Doogie13** [comment]
Is it possible to add a mode which detects CA? So you don't offhand a crystal if you aren't using CA. 

So if you're on offhand crystal and don't have CA enabled it switches offhand to a backup (like a gap). It would also switch off crystal below a certain health. 

Thanks!

**Comment by TechAle** [comment]
Doogie yes, it's possible and quite easy, but i think most of people are going to use another ca (so you can find why i dont think it's a good idea).
With "gapSword", you can simple just click the sword and you have a gapple, this should be enough

**Comment by linustouchtips** [comment]
@TechAle remove the check for a sword in the sword gapple, essentially making it so that if you left click -> a gapple will be moved to offhand and one you finish eating it will switch back. this is a feature in momentum and quite useful

**Comment by TechAle** [comment]
I'll add a check for the sword

**Pull request merged**
