### PR TITLE
Added ability to open chat GUI with command prefix.

### PR DESCRIPTION
**Pull request by Xiaro**
Also formatted code in EventProcessor

### CODE REVIEW

**Review by IUDevman — CHANGES_REQUESTED** [review]
Opening the chat GUI with the command prefix works fine.

We need to double check whether we need some of the removed events. 

An example is in order to have the time stamps work in ChatModifier, we have to post it;s event `ClientChatReceivedEvent`  first in the event manager before using it in the module.

**Comment by IUDevman** [comment]
From the list removed I know we need to keep
```
GuiOpenEvent 
WorldEvent.Unload
PlayerSPPushOutOfBlocksEvent 
LivingDeathEvent 
InputUpdateEvent 
LivingEntityUseItemEvent.Finish
RenderBlockOverlayEvent 
AttackEntityEvent 
ClientChatReceivedEvent 
```

**Comment by Xiaro** [comment]
> Opening the chat GUI with the command prefix works fine.
> 
> We need to double check whether we need some of the removed events.
> 
> An example is in order to have the time stamps work in ChatModifier, we have to post it;s event `ClientChatReceivedEvent` first in the event manager before using it in the module.

Didn't know why are they gone even before the changes but I only reformat the EventProcessor class

> Opening the chat GUI with the command prefix works fine.
> 
> We need to double check whether we need some of the removed events.
> 
> An example is in order to have the time stamps work in ChatModifier, we have to post it;s event `ClientChatReceivedEvent` first in the event manager before using it in the module.

They were removed in this commit
https://github.com/IUDevman/gamesense-client/commit/c1cf7c696684546a6bd6f908901e6430c71275a7

**Comment by IUDevman** [comment]
I'm an idiot lol, merged

**Pull request merged**
