### PR TITLE
added direction and glowing mode to esp

### PR DESCRIPTION
**Pull request by TechAle**
added direction mode and glowing mode to esp
**description:** just 2 new modes to esp, one show the direction of the player and the other it make the player glowing
**Why is this usefull?** Direction mode allow to see where everyone are looking by rotating the esp' square, glowing it's like a chams/wallhack (i'm working for creating a really chams/wallhack that is not glowing)
**Testing** i tested it on singleplayer and on crystalpvp.cc
[click here for the Image of direction mode](https://ibb.co/ggMg6Qs)
[click here for the Image of glowing mode](https://ibb.co/MhPpv8g)

### CODE REVIEW

**Comment by yagel15637** [comment]
I can't really see how Direction Mode works, care to give us a video example? I like Glowing Mode a lot though, this seems really nice!

**Comment by TechAle** [comment]
yagel i used matrix rotation and  everything has a line of comments, i think you need some basic math for understanding.
If you want i can send to you the paper where i calculated this

**Comment by TechAle** [comment]
ok, i'll take some minutes for explaining to you how it works:
first of all we need the direction of the player and his box (x1,x2,y1,y2,z1,z2)[entity.getEntityBoundingBox(), playerColor, ((EntityPlayer) entity).rotationYawHead]
After this, we need to get the center of this box.
Because we want to rotate only in 2 dimension, we are gonna to exclude the y from the rotation.
We take the center of this box with: Xm = x1 + (x2 - x1) / 2 ; Zm = z1 + (z2 - z1) / 2
Then we have to rotate.
Now imagine a 2d plain plane. we have this square (x1,x2,z1,z2) with his own center, we want to rotate this square from his center but, if we rotate with these coordinates, we are gonna rotate not from the center of the square but from the center of the plane (0,0).
Because of that, we have to substract the center from the x and z so it's like to translate our points to the center (x -= xCenter;z -= zCenter;)
Then a simple 2d rotation: 
double rotateX = x * Math.cos(rotation) - z * Math.sin(rotation);
double rotateZ = x * Math.sin(rotation) + z * Math.cos(rotation);
(if you dont understand this, read this: https://en.wikipedia.org/wiki/Rotation_matrix)
At this point we have to return to the original square center, se we have to sum (rotateX += xCenter; rotateZ += zCenter;)
We have every rotate points, now we have to draw everythings
drawLine(square.getPoint(i).x, square.yMin, square.getPoint(i).z,
					square.getPoint((i + 1) % 4).x, square.yMin, square.getPoint((i + 1) % 4).z,
					color
			);
if you dont understand why this: (i + 1) % 4
this is why: 1 % 4 = 1 | 2 % 4 = 2 | 3 % 4 = 3 | 4 % 4 = 0
i use to do this because i'm used to my teacher want everything cleaner and optimized if you want a really good mark, so i'm used to this

tell me if everything now is fine, if yes i'll close

**Comment by yagel15637** [comment]
Oh no I understood how it worked lol, I meant I couldn't see how it was moving based on the player's direction, I wanted a video example to see how it worked

**Pull request closed without merging**
